setting:
  save_dir: experiment                                                          # Attention 1: saving folder name
  pretrained_model_dir: 'pretrained_models/ffhq_msm_p04_noise0_0_img128.pt'     # Attention 2: path for the pretrained model
  dataset_dir: 'datasets/ffhq_samples'                                          # Attention 3: path for the dataset           
  is_demo: True
  solve_inverse_problem: True
  measurement_noise_level: 0.01
  inverse_problem_type: super_resolution                                        # [box_inpainting, super_resolution]
  inverse_problem_solver: measurement_diffusion                                 # measurement noise level for the inverse problem
  stepsize_likelihood: 1.75                                                     # Attention 4: stepsize for the likelihood term     
  stochastic_loop: 2                                                            # Attention 5: the number of stochastic loops for MSM
  num_samples: 5                                                                # The number of samples to be reconstructed
  batch_size: 1
  num_workers: 1

dataset:
  dataset_name: ffhq
  mask_pattern: "random_box"                                                    # ['randomly_cartesian', 'uniformly_cartesian']
  acceleration_rate: 0.4                                                        # Pixel dropping ratio p for the measurement diffusion

vp_diffusion:
  diffusion_predtype: pred_xstart                                               # While model used in MSM framework predicts $\epsilon$, this configuration should be set pred_xstart. 
  noise_schedule: linear
  latent_type: image_space                                                      # [image_space, measurement_space]
  diffusion_model_type: measurement_diffusion                                   # [unconditional_diffusion, measurement_diffusion]
  image_size: 128
  microbatch: -1
  learn_sigma: False
  in_channels: 3
  cond_channels: 0
  num_channels: 128
  num_res_blocks: 2
  channel_mult: ""
  class_cond: False
  use_checkpoint: False
  attention_resolutions: "32,16,8"
  num_heads: 4
  num_head_channels: 64
  num_heads_upsample: -1
  use_scale_shift_norm: True
  dropout: 0.0
  resblock_updown: True
  use_fp16: False
  use_new_attention_order: False
  use_ddim: True
  ddim_eta: 0.85
  timestep_respacing: 'ddim200'
  clip_denoised: False


inverse_problems:
  fastmri_reconstruction:
    name: fastmri_reconstruction

  gaussian_blur:
    name: gaussian_blur
    kernel_size: 61
    intensity: 3.0

  box_inpainting:
    name: inpainting
    mask_opt:
      mask_type: box
      mask_len_range: !!python/tuple [64, 65]  # for box [128, 129]
      #mask_prob_range: !!python/tuple [0.3, 0.7]  # for random
      image_size: 128
  
  random_inpainting:
    name: inpainting
    mask_opt:
      mask_type: random
      mask_prob_range: !!python/tuple [0.85, 0.85]  # for random
      image_size: 128

  motion_blur:
    name: motion_blur
    kernel_size: 61
    intensity: 0.5

  super_resolution: 
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 128, 128]
    scale_factor: 4
  
  colorization: 
    name: colorization

inverse_problem_solvers:
  dps:
    method: dps
    params:
      scale: 1.1
  dds:
    method: dds
    params:
      gamma: 0.95
      CG_iters: 5
  ddnm:
      method: ddnm
      params:
        gamma: 0

  measurement_diffusion:
      method: measurement_diffusion
      params:
        num_stochastics: -1

train:
  lr: 0.00005
  training_data_noiselevel: 0.0

