setting:
  save_dir: experiment                                                          # Attention 1: saving folder name
  pretrained_model_dir: 'pretrained_models/fmri_msm_R4_noise0_0_img256.pt'      # Attention 2: path for the pretrained model
  dataset_dir: 'datasets/fmri_samples'                                          # Attention 3: path for the dataset     
  is_demo: True
  solve_inverse_problem: False
  stochastic_loop: 3                                                            # Attention 4: the number of stochastic loops for MSM           
  num_samples: 3000                                                             # Attention 5: the number of samples to be generated
  batch_size: 1
  num_workers: 1

dataset:
  dataset_name: fastmri
  mask_pattern: "randomly_cartesian"                                            # ['randomly_cartesian', 'uniformly_cartesian']
  acceleration_rate: 4                                                          # acceleration rate R for the measurement diffusion

vp_diffusion:
  diffusion_predtype: pred_xstart                                               # While model used in MSM framework predicts $\epsilon$, this configuration should be set pred_xstart.
  latent_type: measurement_space                                                # [image_space, measurement_space]
  noise_schedule: linear
  diffusion_model_type: measurement_diffusion                                   # [unconditional_diffusion, measurement_diffusion]
  image_size: 256
  microbatch: -1
  learn_sigma: False
  in_channels: 2
  cond_channels: 0
  num_channels: 128
  # num_res_blocks: 1
  num_res_blocks: 2
  channel_mult: ""
  class_cond: False
  use_checkpoint: False
  attention_resolutions: "32,16,8"
  num_heads: 4
  num_head_channels: 64
  num_heads_upsample: -1
  use_scale_shift_norm: True
  dropout: 0.0
  resblock_updown: True
  use_fp16: False
  use_new_attention_order: False
  use_ddim: True
  ddim_eta: 1.00
  timestep_respacing: 'ddim200'
  clip_denoised: False

train:
  lr: 0.0001
  training_data_noiselevel: 0.0