setting:
  save_dir: experiment                                                          # Attention 1: saving folder name
  pretrained_model_dir: ''                                                      
  dataset_dir: 'datasets/fmri_samples'                                          # Attention 2: path for the dataset 
  is_demo: True
  save_interval: 50000                                                          # Save the model every 50000 iterations    
  log_interval: 1000                                                            # Log the training process every 1000 iterations
  batch_size: 2                                                                 # Attention 3: batch size for training (Set 1 for sampling)
  microbatch: 2                                                                 # Attention 4: microbatch size for splitting the batch to fit GPU memory constraints.
  num_workers: 1

train:
  lr: 0.00005
  training_data_noiselevel: 0.0                                                 # noise level of the training data    
  tau_SURE: 0.0
  lr_SURE: 0.0

dataset:
  dataset_name: fastmri
  mask_pattern: "randomly_cartesian"                                            # ['randomly_cartesian', 'uniformly_cartesian']
  acceleration_rate: 1

vp_diffusion:
  diffusion_predtype: epsilon
  latent_type: image_space                                                      # [image_space, measurement_space]
  noise_schedule: linear
  diffusion_model_type: unconditional_diffusion                                 # [unconditional_diffusion, measurement_diffusion]
  image_size: 256
  learn_sigma: False
  in_channels: 2
  cond_channels: 0
  num_channels: 128
  num_res_blocks: 2
  channel_mult: ""
  class_cond: False
  use_checkpoint: False
  attention_resolutions: "32,16,8"
  num_heads: 4
  num_head_channels: 64
  num_heads_upsample: -1
  use_scale_shift_norm: True
  dropout: 0.0
  resblock_updown: True
  use_fp16: False
  use_new_attention_order: False
  model_path: ''
  use_ddim: false
  timestep_respacing: ''
  clip_denoised: True

